CREATE TABLE IF NOT EXISTS channel_sessions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name VARCHAR(255)      NOT NULL,
    genre        VARCHAR(255)      NOT NULL DEFAULT '',
    url          VARCHAR(255)      NOT NULL DEFAULT '',
    description  VARCHAR(255)      NOT NULL DEFAULT '',
    comment      VARCHAR(255)      NOT NULL DEFAULT '',
    content_type VARCHAR(32)       NOT NULL DEFAULT '',
    tracker_ip   VARCHAR(45)       NOT NULL DEFAULT '',  -- tracker hit の GlobalAddr.IP（IPv4/IPv6）
    started_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ended_at     TIMESTAMP WITHOUT TIME ZONE NULL         -- NULL = 配信中
);

CREATE INDEX IF NOT EXISTS idx_channel_name ON channel_sessions (channel_name);

CREATE TABLE IF NOT EXISTS channel_snapshots (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       BIGINT            NOT NULL,  -- channel_sessions.id
    channel_id       CHAR(32)          NOT NULL DEFAULT '',  -- 履歴参照用（hex文字列）
    recorded_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    listeners        INTEGER           NOT NULL DEFAULT 0,
    relays           INTEGER           NOT NULL DEFAULT 0,
    age              BIGINT            NOT NULL DEFAULT 0,  -- tracker hit の UpTime (秒)
    name             VARCHAR(255)      NOT NULL DEFAULT '',
    bitrate          INTEGER           NOT NULL DEFAULT 0,
    genre            VARCHAR(255)      NOT NULL DEFAULT '',
    url              VARCHAR(255)      NOT NULL DEFAULT '',
    description      VARCHAR(255)      NOT NULL DEFAULT '',
    comment          VARCHAR(255)      NOT NULL DEFAULT '',
    content_type     VARCHAR(32)       NOT NULL DEFAULT '',
    hidden_listeners BOOLEAN           NOT NULL DEFAULT FALSE,
    track_title      VARCHAR(255)      NOT NULL DEFAULT '',
    track_artist     VARCHAR(255)      NOT NULL DEFAULT '',
    track_contact    VARCHAR(255)      NOT NULL DEFAULT '',
    track_album      VARCHAR(255)      NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_session_time ON channel_snapshots (session_id, recorded_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_recorded_at_name ON channel_snapshots (recorded_at, name);
